# Application
spring.application.name=payflow-api
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/payflow_db
spring.datasource.username=postgres
spring.datasource.password=whypost
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT (we'll use this later)
jwt.secret=payflow_secret_key_change_this_in_production_minimum_32_characters
jwt.expiration=86400000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html